#!/usr/bin/env -S npx tsx
// Generates supabase/seed.sql from the structured seed data files, using
// parameter-free but properly escaped SQL literals (never string-concat
// untrusted input - this data is developer-authored, but we still escape
// correctly rather than trusting apostrophe-free content).
import { writeFileSync, readdirSync, statSync, readFileSync } from "fs";
import { join, extname } from "path";
import { imageSize } from "image-size";

import { PAGES_CONTENT } from "./seed-pages-content";
import { SITE_SETTINGS, LISTINGS } from "./seed-settings-listings";
import { SR_NEIGHBOURHOODS } from "../lib/neighbourhoods-data";
import { BLOG_POSTS } from "../lib/blog-data";

const CITY_MASTER_IMAGE: Record<string, string> = {
  Milton: "/images/city-milton.png",
  Oakville: "/images/city-oakville.png",
  Burlington: "/images/city-burlington.png",
  Mississauga: "/images/neighbourhoods-hero.png",
  Kitchener: "/images/neighbourhoods-hero.png",
};

function sqlStr(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  return "'" + String(value).replace(/'/g, "''") + "'";
}
function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}
function sqlNum(value: number | null | undefined): string {
  return value === null || value === undefined ? "NULL" : String(value);
}
function sqlJson(value: unknown): string {
  return "'" + JSON.stringify(value).replace(/'/g, "''") + "'::jsonb";
}

const lines: string[] = [];
lines.push("-- Generated by scripts/generate-seed-sql.ts. Do not hand-edit -");
lines.push("-- change the seed-*.ts / lib/*-data.ts sources and regenerate instead.");
lines.push("-- Idempotent: safe to re-run (truncates and reinserts every table).");
lines.push("");
lines.push("truncate table public.pages, public.neighbourhoods, public.blog_posts, public.site_settings, public.media, public.listings restart identity cascade;");
lines.push("");

// ---------------------------------------------------------------------------
// pages
// ---------------------------------------------------------------------------
lines.push("-- pages (" + PAGES_CONTENT.length + " rows)");
for (const p of PAGES_CONTENT) {
  lines.push(
    `insert into public.pages (slug, title, content, seo_title, seo_description, status) values (` +
      [sqlStr(p.slug), sqlStr(p.title), sqlJson(p.content), sqlStr(p.seo_title), sqlStr(p.seo_description), sqlStr("published")].join(", ") +
      `);`
  );
}
lines.push("");

// ---------------------------------------------------------------------------
// neighbourhoods
// ---------------------------------------------------------------------------
const entries = Object.entries(SR_NEIGHBOURHOODS);
const cityCounters: Record<string, number> = {};
lines.push("-- neighbourhoods (" + entries.length + " rows)");
for (const [slug, data] of entries) {
  const order = (cityCounters[data.city] ?? 0);
  cityCounters[data.city] = order + 1;
  const cols = [
    "slug", "name", "city", "headline", "description", "lifestyle", "schools",
    "commute", "seo_title", "seo_description", "status", "display_order",
  ];
  const vals = [
    sqlStr(slug),
    sqlStr(data.name),
    sqlStr(data.city),
    sqlStr(data.tagline),
    sqlStr(data.body),
    sqlStr(data.parks),
    sqlStr(data.schools),
    sqlStr(data.commute),
    sqlStr(`${data.name} Real Estate — Saigal Realty Inc., Brokerage`),
    sqlStr(data.tagline),
    sqlStr("published"),
    sqlNum(order),
  ];
  lines.push(`insert into public.neighbourhoods (${cols.join(", ")}) values (${vals.join(", ")});`);
}
lines.push("");

// ---------------------------------------------------------------------------
// blog_posts
// ---------------------------------------------------------------------------
lines.push("-- blog_posts (" + BLOG_POSTS.length + " rows)");
const SEED_TODAY = new Date("2026-09-16T09:00:00Z");
BLOG_POSTS.forEach((post, i) => {
  const publishedAt = new Date(SEED_TODAY.getTime() - i * 3 * 24 * 60 * 60 * 1000);
  const cols = [
    "slug", "title", "category", "excerpt", "body", "featured_image", "author",
    "published_at", "cta_label", "cta_href", "seo_title", "seo_description", "status",
  ];
  const vals = [
    sqlStr(post.slug),
    sqlStr(post.title),
    sqlStr(post.category),
    sqlStr(post.excerpt),
    sqlStr(post.paragraphs.join("\n\n")),
    sqlStr(post.image),
    sqlStr("Saigal Realty Team"),
    sqlStr(publishedAt.toISOString()),
    sqlStr(post.cta.text),
    sqlStr(post.cta.href),
    sqlStr(`${post.title} — Saigal Realty Inc., Brokerage`),
    sqlStr(post.excerpt),
    sqlStr("published"),
  ];
  lines.push(`insert into public.blog_posts (${cols.join(", ")}) values (${vals.join(", ")});`);
});
lines.push("");

// ---------------------------------------------------------------------------
// site_settings
// ---------------------------------------------------------------------------
lines.push("-- site_settings (singleton)");
{
  const s = SITE_SETTINGS;
  const cols = [
    "id", "brokerage_name", "phone", "email", "address_line1", "address_line2",
    "social_instagram", "social_facebook", "social_linkedin", "footer_tagline",
    "copyright_text", "contact_form_destination_email", "logo_url", "favicon_url",
  ];
  const vals = [
    "1", sqlStr(s.brokerage_name), sqlStr(s.phone), sqlStr(s.email), sqlStr(s.address_line1), sqlStr(s.address_line2),
    sqlStr(s.social_instagram), sqlStr(s.social_facebook), sqlStr(s.social_linkedin), sqlStr(s.footer_tagline),
    sqlStr(s.copyright_text), sqlStr(s.contact_form_destination_email), sqlStr(s.logo_url), sqlStr(s.favicon_url),
  ];
  lines.push(`insert into public.site_settings (${cols.join(", ")}) values (${vals.join(", ")});`);
}
lines.push("");

// ---------------------------------------------------------------------------
// listings
// ---------------------------------------------------------------------------
lines.push("-- listings (" + LISTINGS.length + " rows)");
for (const l of LISTINGS) {
  const cols = [
    "address", "city", "neighbourhood", "price", "beds", "baths", "property_type",
    "description", "image", "listing_url", "featured", "status",
  ];
  const vals = [
    sqlStr(l.address), sqlStr(l.city), sqlStr(l.neighbourhood), sqlNum(l.price), sqlNum(l.beds), sqlNum(l.baths),
    sqlStr(l.property_type), sqlStr(l.description), sqlStr(l.image), sqlStr(l.listing_url),
    sqlBool(l.featured), sqlStr("published"),
  ];
  lines.push(`insert into public.listings (${cols.join(", ")}) values (${vals.join(", ")});`);
}
lines.push("");

// ---------------------------------------------------------------------------
// media (metadata catalog - scans public/images and public/uploads)
// ---------------------------------------------------------------------------
const PUBLIC_ROOT = join(__dirname, "..", "public");
const MIME_BY_EXT: Record<string, string> = { ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp", ".svg": "image/svg+xml" };

type MediaRow = { filename: string; storage_path: string; alt_text: string | null; mime_type: string | null; width: number | null; height: number | null; file_size: number };
const mediaRows: MediaRow[] = [];
for (const dir of ["images", "uploads"]) {
  const abs = join(PUBLIC_ROOT, dir);
  let files: string[];
  try {
    files = readdirSync(abs);
  } catch {
    continue;
  }
  for (const filename of files) {
    const ext = extname(filename).toLowerCase();
    if (!(ext in MIME_BY_EXT)) continue;
    const full = join(abs, filename);
    const stat = statSync(full);
    let width: number | null = null;
    let height: number | null = null;
    try {
      const dim = imageSize(readFileSync(full));
      width = dim.width ?? null;
      height = dim.height ?? null;
    } catch {
      // leave null if unreadable
    }
    mediaRows.push({
      filename,
      storage_path: `/${dir}/${filename}`,
      alt_text: null,
      mime_type: MIME_BY_EXT[ext],
      width,
      height,
      file_size: stat.size,
    });
  }
}
lines.push("-- media (" + mediaRows.length + " rows, metadata catalog only - files still served from /public in this phase)");
for (const m of mediaRows) {
  const cols = ["filename", "storage_path", "alt_text", "mime_type", "width", "height", "file_size"];
  const vals = [sqlStr(m.filename), sqlStr(m.storage_path), sqlStr(m.alt_text), sqlStr(m.mime_type), sqlNum(m.width), sqlNum(m.height), sqlNum(m.file_size)];
  lines.push(`insert into public.media (${cols.join(", ")}) values (${vals.join(", ")});`);
}
lines.push("");

const outPath = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n") + "\n", "utf-8");

console.log(`Wrote ${outPath}`);
console.log(`  pages: ${PAGES_CONTENT.length}`);
console.log(`  neighbourhoods: ${entries.length}`);
console.log(`  blog_posts: ${BLOG_POSTS.length}`);
console.log(`  site_settings: 1`);
console.log(`  listings: ${LISTINGS.length}`);
console.log(`  media: ${mediaRows.length}`);
console.log("  city counts:", cityCounters);
